version: '3'

services:
  database:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Microsoft2017"
    volumes:
     - "./database:/workspace"
    command:
      - /workspace/database-entrypoint.sh
  goapp:
    build: ./goapp
    volumes:
      - ./goapp:/app/goapp # for live code updates
    depends_on:
      - database
